apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels" .  | indent 3}}
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      {{- include "selector" .  | indent 6}}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "selector" . | indent 6 }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: app
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources: {}
status: {}

