apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels" .  | indent 3}}
  name: {{ .Release.Name}}-service
spec:
  ports:
  - port: {{ .Values.service.port}}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort}}
  selector:
     {{- include "selector" . | indent 3 }}
  type: {{ .Values.service.type}}
status:
  loadBalancer: {}
